Add files via upload
qwqVictor/Redrock-SRE-2022-Ops-Winter-Assessment pull request #1
Opened 2022-02-08 17:16 UTC by nohideplace

上传成功请告诉我2271094299@qq.com

2022-02-10 10:45 UTC, qwqVictor commented
注意一下完成度：
「**有基本的异常处理能力，例如编译错误时能够不执行接下来的步骤等。**」这里想一下哪些步骤是关键的，一旦失败需要终止的，处理一下。善用 `&&` 和返回值判断。
「**若使用 shell 实现，必须能够直接通过 shellcheck。**」注意一下编码习惯。去 https://shellcheck.net 检查一下。

2022-02-21 15:16 UTC, qwqVictor requested changes
还是继续改进一下吧，认为完善的差不多的时候从这里敲一下我

2022-02-21 15:16 UTC, qwqVictor commented on Q3/2021212630/install.txt
> +(cat local | grep -o [0-9][0-9].[0-9]) &> local
这个地方其实你完全可以只使用 shell 变量，并不需要引入文件。
比如:
```shell
ngx_version="$(/usr/local/nginx/sbin/nginx -v)"
ngx_version="$(printf "%s" "${ngx_version}" | grep -o '[0-9][0-9].[0-9]')"
```
然后你后面就可以用 ngx_version 这个变量了。

cat 一个文件再写回原文件这个操作也明显有问题，因为这样得到的应该是个空文件，仔细思考一下 `>` 的行为。

这个 commit 的版本 bug 有点大，注意一下，而且也明显没有过 shellcheck。

2022-02-22 05:04 UTC, nohideplace commented
改了一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Victor ***@***.***&gt;; 
发送时间: 2022年2月21日(星期一) 晚上11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qwqVictor/Redrock-SRE-2022-Ops-Winter-Assessment] Add files via upload (PR #1)





 
@qwqVictor requested changes on this pull request.
 
还是继续改进一下吧，认为完善的差不多的时候从这里敲一下我

 
In Q3/2021212630/install.txt:
 &gt;  /usr/local/nginx/sbin/nginx -v &amp;&gt; local -echo `cat local | grep -o [0-9][0-9].[0-9]` &gt; local +(cat local | grep -o [0-9][0-9].[0-9]) &amp;&gt; local  
这个地方其实你完全可以只使用 shell 变量，并不需要引入文件。
 比如:
 ngx_version="$(/usr/local/nginx/sbin/nginx -v)" ngx_version="$(printf "%s" "${ngx_version}" | grep -o '[0-9][0-9].[0-9]')"
 
然后你后面就可以用 ngx_version 这个变量了。
 
cat 一个文件再写回原文件这个操作也明显有问题，因为这样得到的应该是个空文件，仔细思考一下 &gt; 的行为。
 
这个 commit 的版本 bug 有点大，注意一下，而且也明显没有过 shellcheck。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were assigned.Message ID: ***@***.***&gt;

2022-02-22 09:50 UTC, qwqVictor approved these changes

2022-02-23 05:52 UTC, merged